name: ci python

on:
   push:
     branches: [main]
   pull_request:
     branches: [main]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkouts@4
      - name: Set Up python
        uses: actions/setup-python@4
        with:
          python-version: '3.x'
      - name: Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
      - name: Run linting
        run: flake8  log_finder.py
      - name: Run test
        run: pytest test_log_finder